### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It
provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object,
while a DataFrame is a two-dimensional, size-mutable, and potewtially heterogeneous tabular data structure
with labeled axes (rows and columns).

In [2]:
!pip install pandas

Requirement already satisfied: pandas in .\venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in .\venv\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in .\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd

## Series - is a one dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). The axis labels are collectively referred to as the index. A Series is like a fixed-size dict in that you can get and set values by index label.

data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [5]:
## Create Series from a dictionary 

data_dict = {'a': 1, 'b': 2, 'c': 3}
series_dict = pd.Series(data_dict)
print(series_dict)
print(type(series_dict))

a    1
b    2
c    3
dtype: int64
<class 'pandas.Series'>

In [ ]:
data = [10 , 20, 30, 40, 50]
## Alternative way - index = [1 , 2 , 3 , 4 , 5]
## series = pd.Series(data, index=index)
series = pd.Series(data, index=[1, 2, 4, 5, 6])
print(series)

1    10
2    20
4    30
5    40
6    50
dtype: int64

In [9]:
## DataFrame 
## Create a dataframe from a dictionary of lists

data = {
    "Name": ["Shaurya" , "Rohit" , "Ramesh" , "Suresh"],
    "Age": [25, 30, 35, 40],
    "City": ["New York", "Los Angeles", "Chicago", "Houston"]
}

df = pd.DataFrame(data , index = [1 , 2 , 3 ,4])
print(df)

      Name  Age         City
1  Shaurya   25     New York
2    Rohit   30  Los Angeles
3   Ramesh   35      Chicago
4   Suresh   40      Houston

In [19]:
## Create a datafram from a list of dictionaries

data = [
    {"Name": "Shaurya", "Age": 25, "City": "New York"},
    {"Name": "Rohit", "Age": 30, "City": "Los Angeles"},
    {"Name": "Ramesh", "Age": 35, "City": "Chicago"},
    {"Name": "Suresh", "Age": 40, "City": "Houston"}
]

df = pd.DataFrame(data , index = [1 , 2 , 3 ,4])
print(df)

      Name  Age         City
1  Shaurya   25     New York
2    Rohit   30  Los Angeles
3   Ramesh   35      Chicago
4   Suresh   40      Houston

In [14]:
## DataFrame - is a two-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dict of Series objects. It is generally the most commonly used pandas object.

df = pd.read_csv('../data/data.csv')
df.head(10)

,OrderID,OrderDate,CustomerID,Product,Category,Quantity,UnitPrice,DiscountPercent,Revenue,Region,PaymentMethod,OrderStatus
0,ORD00001,2026-06-13,CUST1228,Smartphone,Electronics,1,583,5,553.85,South,Wallet,Delivered
1,ORD00002,2026-06-23,CUST1032,Camera,Electronics,1,1229,15,1044.65,North,Credit Card,Shipped
2,ORD00003,2026-03-01,CUST1203,Camera,Electronics,5,74,20,296.00,West,Debit Card,Returned
3,ORD00004,2026-05-31,CUST1348,Mouse,Accessories,1,346,15,294.10,East,Debit Card,Shipped
4,ORD00005,2026-03-28,CUST1367,Smartphone,Electronics,1,798,0,798.00,East,Cash on Delivery,Cancelled
5,ORD00006,2026-01-12,CUST1080,Smartwatch,Wearables,5,275,15,1168.75,East,Wallet,Cancelled
6,ORD00007,2026-05-28,CUST1791,Keyboard,Accessories,1,113,5,107.35,East,Credit Card,Shipped
7,ORD00008,2026-01-26,CUST1166,Tablet,Electronics,3,948,10,2559.60,East,UPI,Shipped
8,ORD00009,2026-06-21,CUST1546,Mouse,Accessories,1,1267,5,1203.65,South,Debit Card,Returned
9,ORD00010,2026-04-08,CUST1863,Mouse,Accessories,5,469,10,2110.50,North,Debit Card,Delivered

In [20]:
## Accessing Data from dataframe
df

      Name  Age         City
1  Shaurya   25     New York
2    Rohit   30  Los Angeles
3   Ramesh   35      Chicago
4   Suresh   40      Houston

In [21]:
df['Name']  ## Accessing a single column

1    Shaurya
2      Rohit
3     Ramesh
4     Suresh
Name: Name, dtype: str

In [23]:
df.loc[1]  ## Accessing a single row by index

Name     Shaurya
Age           25
City    New York
Name: 1, dtype: object

In [24]:
df.iloc[0]  ## Accessing a single row by index using iloc

Name     Shaurya
Age           25
City    New York
Name: 1, dtype: object

In [ ]:
df.at[1 , 'Age'] ## Accessing a single value by row and column label

np.int64(25)

In [27]:
df.iat[2,2] ## Accessing a single value by row and column index using iat

'Chicago'

In [28]:
df

      Name  Age         City
1  Shaurya   25     New York
2    Rohit   30  Los Angeles
3   Ramesh   35      Chicago
4   Suresh   40      Houston

In [29]:
df['Salary'] = [50000, 60000, 70000, 80000] ## Adding a new column to the dataframe

In [30]:
df

      Name  Age         City  Salary
1  Shaurya   25     New York   50000
2    Rohit   30  Los Angeles   60000
3   Ramesh   35      Chicago   70000
4   Suresh   40      Houston   80000

In [31]:
df.drop('Salary', axis=1, inplace=True) ## Dropping a column from the dataframe

In [32]:
df

      Name  Age         City
1  Shaurya   25     New York
2    Rohit   30  Los Angeles
3   Ramesh   35      Chicago
4   Suresh   40      Houston

In [34]:
df['Age'] = df['Age']+1 ## Updating a column in the dataframe
df

      Name  Age         City
1  Shaurya   27     New York
2    Rohit   32  Los Angeles
3   Ramesh   37      Chicago
4   Suresh   42      Houston

In [35]:
df.describe() ## Summary statistics of the dataframe

             Age
count   4.000000
mean   34.500000
std     6.454972
min    27.000000
25%    30.750000
50%    34.500000
75%    38.250000
max    42.000000