### Data Manipulation and Analysis with Pandas

Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a
wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract
insights from data. In this lesson, we will cover various data manipulation and analysis techniques using Pandas.

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv('../data/data.csv')
## fetch the first 5 rows of the dataframe
df.head(5)

,OrderID,OrderDate,CustomerID,Product,Category,Quantity,UnitPrice,DiscountPercent,Revenue,Region,PaymentMethod,OrderStatus
0,ORD00001,2026-06-13,CUST1228,Smartphone,Electronics,1,583,5,553.85,South,Wallet,Delivered
1,ORD00002,2026-06-23,CUST1032,Camera,Electronics,1,1229,15,1044.65,North,Credit Card,Shipped
2,ORD00003,2026-03-01,CUST1203,Camera,Electronics,5,74,20,296.00,West,Debit Card,Returned
3,ORD00004,2026-05-31,CUST1348,Mouse,Accessories,1,346,15,294.10,East,Debit Card,Shipped
4,ORD00005,2026-03-28,CUST1367,Smartphone,Electronics,1,798,0,798.00,East,Cash on Delivery,Cancelled

In [6]:
df.tail(5) ## fetch the last 5 rows of the dataframe

,OrderID,OrderDate,CustomerID,Product,Category,Quantity,UnitPrice,DiscountPercent,Revenue,Region,PaymentMethod,OrderStatus
495,ORD00496,2026-04-23,CUST1012,Laptop,Electronics,1,555,10,499.50,South,Wallet,Cancelled
496,ORD00497,2026-05-13,CUST1677,Camera,Electronics,5,215,15,913.75,South,Net Banking,Cancelled
497,ORD00498,2026-06-19,CUST1055,Tablet,Electronics,2,1163,20,1860.80,North,Wallet,Shipped
498,ORD00499,2026-05-10,CUST1769,Smartwatch,Wearables,4,358,0,1432.00,West,UPI,Shipped
499,ORD00500,2026-03-26,CUST1563,Mouse,Accessories,1,1058,5,1005.10,West,Net Banking,Shipped

In [7]:
df.describe() ## Summary statistics of the dataframe

         Quantity    UnitPrice  DiscountPercent      Revenue
count  500.000000   500.000000       500.000000   500.000000
mean     3.070000   754.962000         9.730000  2089.712900
std      1.418847   421.709719         7.048152  1628.267625
min      1.000000    30.000000         0.000000    29.750000
25%      2.000000   392.750000         5.000000   802.850000
50%      3.000000   742.000000        10.000000  1727.100000
75%      4.000000  1122.500000        15.000000  2965.725000
max      5.000000  1498.000000        20.000000  7220.000000

In [9]:
df.dtypes

OrderID                str
OrderDate              str
CustomerID             str
Product                str
Category               str
Quantity             int64
UnitPrice            int64
DiscountPercent      int64
Revenue            float64
Region                 str
PaymentMethod          str
OrderStatus            str
dtype: object

In [13]:
## Handling missing values

df.isnull().any() ## Check if any row has missing values

OrderID            False
OrderDate          False
CustomerID         False
Product            False
Category           False
Quantity           False
UnitPrice          False
DiscountPercent    False
Revenue            False
Region             False
PaymentMethod      False
OrderStatus        False
dtype: bool

In [14]:
df.isnull().sum() ## Count the number of missing values in each column

OrderID            0
OrderDate          0
CustomerID         0
Product            0
Category           0
Quantity           0
UnitPrice          0
DiscountPercent    0
Revenue            0
Region             0
PaymentMethod      0
OrderStatus        0
dtype: int64

In [16]:
df.fillna(0) ## Fill missing values with 0

,OrderID,OrderDate,CustomerID,Product,Category,Quantity,UnitPrice,DiscountPercent,Revenue,Region,PaymentMethod,OrderStatus
0,ORD00001,2026-06-13,CUST1228,Smartphone,Electronics,1,583,5,553.85,South,Wallet,Delivered
1,ORD00002,2026-06-23,CUST1032,Camera,Electronics,1,1229,15,1044.65,North,Credit Card,Shipped
2,ORD00003,2026-03-01,CUST1203,Camera,Electronics,5,74,20,296.00,West,Debit Card,Returned
3,ORD00004,2026-05-31,CUST1348,Mouse,Accessories,1,346,15,294.10,East,Debit Card,Shipped
4,ORD00005,2026-03-28,CUST1367,Smartphone,Electronics,1,798,0,798.00,East,Cash on Delivery,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD00496,2026-04-23,CUST1012,Laptop,Electronics,1,555,10,499.50,South,Wallet,Cancelled
496,ORD00497,2026-05-13,CUST1677,Camera,Electronics,5,215,15,913.75,South,Net Banking,Cancelled
497,ORD00498,2026-06-19,CUST1055,Tablet,Electronics,2,1163,20,1860.80,North,Wallet,Shipped
498,ORD00499,2026-05-10,CUST1769,Smartwatch,Wearables,4,358,0,1432.00,West,UPI,Shipped
499,ORD00500,2026-03-26,CUST1563,Mouse,Accessories,1,1058,5,1005.10,West,Net Banking,Shipped

In [17]:
df['rev'] = df['Revenue'].fillna(df['Revenue'].mean()) ## Fill missing values in 'rev' column with mean of the column

In [18]:
df

,OrderID,OrderDate,CustomerID,Product,Category,Quantity,UnitPrice,DiscountPercent,Revenue,Region,PaymentMethod,OrderStatus,rev
0,ORD00001,2026-06-13,CUST1228,Smartphone,Electronics,1,583,5,553.85,South,Wallet,Delivered,553.85
1,ORD00002,2026-06-23,CUST1032,Camera,Electronics,1,1229,15,1044.65,North,Credit Card,Shipped,1044.65
2,ORD00003,2026-03-01,CUST1203,Camera,Electronics,5,74,20,296.00,West,Debit Card,Returned,296.00
3,ORD00004,2026-05-31,CUST1348,Mouse,Accessories,1,346,15,294.10,East,Debit Card,Shipped,294.10
4,ORD00005,2026-03-28,CUST1367,Smartphone,Electronics,1,798,0,798.00,East,Cash on Delivery,Cancelled,798.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD00496,2026-04-23,CUST1012,Laptop,Electronics,1,555,10,499.50,South,Wallet,Cancelled,499.50
496,ORD00497,2026-05-13,CUST1677,Camera,Electronics,5,215,15,913.75,South,Net Banking,Cancelled,913.75
497,ORD00498,2026-06-19,CUST1055,Tablet,Electronics,2,1163,20,1860.80,North,Wallet,Shipped,1860.80
498,ORD00499,2026-05-10,CUST1769,Smartwatch,Wearables,4,358,0,1432.00,West,UPI,Shipped,1432.00
499,ORD00500,2026-03-26,CUST1563,Mouse,Accessories,1,1058,5,1005.10,West,Net Banking,Shipped,1005.10

In [19]:
df.dtypes

OrderID                str
OrderDate              str
CustomerID             str
Product                str
Category               str
Quantity             int64
UnitPrice            int64
DiscountPercent      int64
Revenue            float64
Region                 str
PaymentMethod          str
OrderStatus            str
rev                float64
dtype: object

In [22]:
## Renaming column 
df.rename(columns={'rev':'main'}, inplace=True) ## Rename the column 'Revenue' to 'rev'

In [23]:
df

,OrderID,OrderDate,CustomerID,Product,Category,Quantity,UnitPrice,DiscountPercent,main,Region,PaymentMethod,OrderStatus,main
0,ORD00001,2026-06-13,CUST1228,Smartphone,Electronics,1,583,5,553.85,South,Wallet,Delivered,553.85
1,ORD00002,2026-06-23,CUST1032,Camera,Electronics,1,1229,15,1044.65,North,Credit Card,Shipped,1044.65
2,ORD00003,2026-03-01,CUST1203,Camera,Electronics,5,74,20,296.00,West,Debit Card,Returned,296.00
3,ORD00004,2026-05-31,CUST1348,Mouse,Accessories,1,346,15,294.10,East,Debit Card,Shipped,294.10
4,ORD00005,2026-03-28,CUST1367,Smartphone,Electronics,1,798,0,798.00,East,Cash on Delivery,Cancelled,798.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD00496,2026-04-23,CUST1012,Laptop,Electronics,1,555,10,499.50,South,Wallet,Cancelled,499.50
496,ORD00497,2026-05-13,CUST1677,Camera,Electronics,5,215,15,913.75,South,Net Banking,Cancelled,913.75
497,ORD00498,2026-06-19,CUST1055,Tablet,Electronics,2,1163,20,1860.80,North,Wallet,Shipped,1860.80
498,ORD00499,2026-05-10,CUST1769,Smartwatch,Wearables,4,358,0,1432.00,West,UPI,Shipped,1432.00
499,ORD00500,2026-03-26,CUST1563,Mouse,Accessories,1,1058,5,1005.10,West,Net Banking,Shipped,1005.10

In [26]:
## Change Data type of a column

df['main'] = df['main'].astype(int) ## Change the data type of the column 'main' to int
df

,OrderID,OrderDate,CustomerID,Product,Category,Quantity,UnitPrice,DiscountPercent,main,Region,PaymentMethod,OrderStatus,main
0,ORD00001,2026-06-13,CUST1228,Smartphone,Electronics,1,583,5,553,South,Wallet,Delivered,553
1,ORD00002,2026-06-23,CUST1032,Camera,Electronics,1,1229,15,1044,North,Credit Card,Shipped,1044
2,ORD00003,2026-03-01,CUST1203,Camera,Electronics,5,74,20,296,West,Debit Card,Returned,296
3,ORD00004,2026-05-31,CUST1348,Mouse,Accessories,1,346,15,294,East,Debit Card,Shipped,294
4,ORD00005,2026-03-28,CUST1367,Smartphone,Electronics,1,798,0,798,East,Cash on Delivery,Cancelled,798
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD00496,2026-04-23,CUST1012,Laptop,Electronics,1,555,10,499,South,Wallet,Cancelled,499
496,ORD00497,2026-05-13,CUST1677,Camera,Electronics,5,215,15,913,South,Net Banking,Cancelled,913
497,ORD00498,2026-06-19,CUST1055,Tablet,Electronics,2,1163,20,1860,North,Wallet,Shipped,1860
498,ORD00499,2026-05-10,CUST1769,Smartwatch,Wearables,4,358,0,1432,West,UPI,Shipped,1432
499,ORD00500,2026-03-26,CUST1563,Mouse,Accessories,1,1058,5,1005,West,Net Banking,Shipped,1005

In [30]:
df['new'] = df.iloc[:, 8].apply(lambda x: x * 2)
df.head(5)

,OrderID,OrderDate,CustomerID,Product,Category,Quantity,UnitPrice,DiscountPercent,main,Region,PaymentMethod,OrderStatus,main,new
0,ORD00001,2026-06-13,CUST1228,Smartphone,Electronics,1,583,5,553,South,Wallet,Delivered,553,1106
1,ORD00002,2026-06-23,CUST1032,Camera,Electronics,1,1229,15,1044,North,Credit Card,Shipped,1044,2088
2,ORD00003,2026-03-01,CUST1203,Camera,Electronics,5,74,20,296,West,Debit Card,Returned,296,592
3,ORD00004,2026-05-31,CUST1348,Mouse,Accessories,1,346,15,294,East,Debit Card,Shipped,294,588
4,ORD00005,2026-03-28,CUST1367,Smartphone,Electronics,1,798,0,798,East,Cash on Delivery,Cancelled,798,1596

In [31]:
## Data Aggregating and grouping 
df.head(5)

,OrderID,OrderDate,CustomerID,Product,Category,Quantity,UnitPrice,DiscountPercent,main,Region,PaymentMethod,OrderStatus,main,new
0,ORD00001,2026-06-13,CUST1228,Smartphone,Electronics,1,583,5,553,South,Wallet,Delivered,553,1106
1,ORD00002,2026-06-23,CUST1032,Camera,Electronics,1,1229,15,1044,North,Credit Card,Shipped,1044,2088
2,ORD00003,2026-03-01,CUST1203,Camera,Electronics,5,74,20,296,West,Debit Card,Returned,296,592
3,ORD00004,2026-05-31,CUST1348,Mouse,Accessories,1,346,15,294,East,Debit Card,Shipped,294,588
4,ORD00005,2026-03-28,CUST1367,Smartphone,Electronics,1,798,0,798,East,Cash on Delivery,Cancelled,798,1596

In [32]:
grouped_mean = df.groupby('Product')['main'].mean() ## Group by 'Product' and calculate the mean of 'main' column
grouped_mean

                   main         main
Product
Camera      2381.255814  2381.255814
Headphones  2130.880000  2130.880000
Keyboard    2126.666667  2126.666667
Laptop      2228.803922  2228.803922
Monitor     1828.372549  1828.372549
Mouse       2036.672727  2036.672727
Printer     1755.365854  1755.365854
Smartphone  1863.684211  1863.684211
Smartwatch  2211.461538  2211.461538
Tablet      2315.655172  2315.655172

In [33]:
grouped_agg = df.groupby('Category')['main'].agg(['mean','sum','count'])
grouped_agg

                    main
                    mean     sum count         mean     sum count
Category
Accessories  2094.428571  307881   147  2094.428571  307881   147
Electronics  2114.800000  549848   260  2114.800000  549848   260
Office       1755.365854   71970    41  1755.365854   71970    41
Wearables    2211.461538  114996    52  2211.461538  114996    52

In [45]:
### Merging and joining dataframes

df1 = pd.DataFrame({'key': ['A', 'B', 'C', 'D' , 'E'], 'value1': [1, 2, 3, 4 , 5]})
df2 = pd.DataFrame({'key': ['A', 'B', 'C', 'D'], 'value2': [5, 6, 7, 8]})

In [46]:
df1

  key  value1
0   A       1
1   B       2
2   C       3
3   D       4
4   E       5

In [47]:
df2

  key  value2
0   A       5
1   B       6
2   C       7
3   D       8

In [48]:
### Merge Dataframe on the key column

pd.merge(df1, df2, on='key',how="inner") ## Merge the two dataframes on the 'key' column

  key  value1  value2
0   A       1       5
1   B       2       6
2   C       3       7
3   D       4       8

In [49]:

pd.merge(df1, df2, on='key',how="outer")

  key  value1  value2
0   A       1     5.0
1   B       2     6.0
2   C       3     7.0
3   D       4     8.0
4   E       5     NaN

In [50]:

pd.merge(df1, df2, on='key',how="left")

  key  value1  value2
0   A       1     5.0
1   B       2     6.0
2   C       3     7.0
3   D       4     8.0
4   E       5     NaN

In [51]:

pd.merge(df1, df2, on='key',how="right")

  key  value1  value2
0   A       1       5
1   B       2       6
2   C       3       7
3   D       4       8